apiVersion: v2
name: helm-vms
description: A Helm chart for VMS (Visitor Management System)

type: application

version: 1.0.0

appVersion: "1.0"

dependencies:
  - name: "generic-app"
    alias: visitor-management
    condition: visitor-management.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.14"
