visitor-management:
  enabled: true
  nameOverride: visitor-management
  podDisruptionBudget:
    enabled: false
  pods:
    controller: deployment
    image:
      name: gcr.io/its-artifact-commons/visitor-management
      tag: "will-change"
    ports:
      - containerPort: 443
      - containerPort: 80
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: "Development"

      #- name: UseInMemoryDatabase
      #  value: "true"

      - name: ASPNETCORE_URLS
        value: "http://+:80"

      - name: ConnectionStrings__DefaultConnection
        value: "Server=mssql;Database=vms;User=sa;Password=abcdef123paSSorwd;MultipleActiveResultSets=true"

  ingress:
    enabled: false

  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
        name: http

mssql:
  enabled: true
  sapassword: abcdef123paSSorwd
  acceptEula:
    value: "Y"
  edition:
    value: Developer
  persistence:
    enabled: "true"
