apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vms-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP  
spec:
  ingressClassName: nginx #iap-nginx
  tls:
    - hosts:
      - {{ .Values.domain }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vms-{{ .Values.envAlias }}-visitor-management
                port:
                  name: http
